### ISSUE TITLE
X1 Extreme gen 3

### ISSUE THREAD

**Issue by dharmatech** [nikolasgd/TPFanControl-dual-fan#4]
Hello,

I had been using this version:

https://github.com/Shuzhengz/TPFanCtrl2

However, sometimes I noticed that although the GUI indicated 0 RPM, the right fan was still running.

I'm giving your version a whirl. Will let you know how it goes. :-)

**Comment by dharmatech** [comment]
Just for reference, here's the level values I have in my ini file:
```
Level=50 0 
Level=60 0
Level=65 0
Level=75 1
Level=80 3 
Level=90 7
```

**Comment by nikolasgd** [comment]
Unfortunately, with one of the recent BIOS updates on my P1 Gen 3, my forked version stopped working and I currently don't have the time to fix this.

Please do report back if it works on your machine.

**Comment by dharmatech** [comment]
@nikolasgd

Niko,

Yup, it's been working great on my system!

![image](https://user-images.githubusercontent.com/20816/139882943-e11c9eda-42e5-466b-a7c2-3ec672f8a202.png)

I'm sorry to hear it's not working on yours. :-/ That makes me not want to update the BIOS again before confirming that TPFanControl works! 😬

My system:

![image](https://user-images.githubusercontent.com/20816/139884893-30ffca46-234f-42f5-be53-90095f8b7be2.png)

**Comment by dharmatech** [comment]
@nikolasgd

> Unfortunately, with one of the recent BIOS updates on my P1 Gen 3, my forked version stopped working and I currently don't have the time to fix this.

Niko,

As you can see in the screenshot above, I'm using BIOS 1.18.

According the Lenovo support, that's the latest version for P1G3 and X1EG3:

![image](https://user-images.githubusercontent.com/20816/139923629-eac28a52-097e-4b02-80b8-cfe77ba0f989.png)

What BIOS version are you using?

If you're on 1.18, it would seem odd that it's not working for your P1G3 but it is on my X1EG3.

**Comment by nikolasgd** [comment]
No problems so far with the latest windows update. Closing this issue.
